### ISSUE TITLE
Open Source

### ISSUE THREAD

**Issue by jcubic** [php-strictus/strictus#24]
IS this project Open Source? I don't see a license, which means that it is source available and no one use the code because of the copyright.

**Comment by WendellAdriel** [comment]
The license file was missing, just added it.
BTW, "no one use the code because of the copyright" - I think you didn't check the downloads, they're not much, but this is already being used by some people.

**Comment by jcubic** [comment]
Yes, but all people that did download violate the copyright. Most people have no idea about copyright.
